### ISSUE TITLE
HE 1.22.4.11 无法启动

### ISSUE THREAD

**Issue by a1ive** [Faintsnow/HE#2]
安装 HE 1.22.4.11 之后卡死在 "检测处理器信息" 的启动界面，如图：
![1](https://user-images.githubusercontent.com/10670106/166917937-c0a91772-e959-4dac-b2c7-096522513218.png)

1.22.02.25 及之前版本全部正常。
系统：Win10 19041 (64位)
使用 1.22.02.25 导出的 CPU 信息报告：
[report.txt](https://github.com/Faintsnow/HE/files/8630981/report.txt)

**Comment by Faintsnow** [comment]
> 安装 HE 1.22.4.11 之后卡死在 "检测处理器信息" 的启动界面，如图： ![1](https://user-images.githubusercontent.com/10670106/166917937-c0a91772-e959-4dac-b2c7-096522513218.png)
> 
> 1.22.02.25 及之前版本全部正常。 系统：Win10 19041 (64位) 使用 1.22.02.25 导出的 CPU 信息报告： [report.txt](https://github.com/Faintsnow/HE/files/8630981/report.txt)
[HE_v1.22.5.3_Portable.zip](https://github.com/Faintsnow/HE/files/8631396/HE_v1.22.5.3_Portable.zip)
How about this one?

**Comment by a1ive** [comment]
> [HE_v1.22.5.3_Portable.zip](https://github.com/Faintsnow/HE/files/8631396/HE_v1.22.5.3_Portable.zip)
> How about this one?

It still does not work either.

![1](https://user-images.githubusercontent.com/10670106/166933988-d8dbda3e-ceb7-4162-8d45-2730e902f02d.png)

**Comment by Faintsnow** [comment]
Seems need living debug to check what happend...

**Comment by a1ive** [comment]
> Seems need living debug to check what happend...

How can I contact you? Using QQ?

**Comment by Faintsnow** [comment]
> > Seems need living debug to check what happend...
> 
> How can I contact you? Using QQ?

There is not much difference between v0411 and v0225. 
So you can you v0225 instead of v0411.

BTW,could you help provide smbios and spd summary via v0225?
Thanks.

**Comment by a1ive** [comment]
> > > Seems need living debug to check what happend...
> > 
> > 
> > How can I contact you? Using QQ?
> 
> There is not much difference between v0411 and v0225. So you can you v0225 instead of v0411.
> 
> BTW,could you help provide smbios and spd summary via v0225? Thanks.

[report.txt](https://github.com/Faintsnow/HE/files/8641317/report.txt)

![1](https://user-images.githubusercontent.com/10670106/167151660-dd4e14a9-65f2-4b5b-a36a-6cf3873398eb.png)
typo?  loged => logged

**Comment by Faintsnow** [comment]
> 
[HE_Test0506_1.zip](https://github.com/Faintsnow/HE/files/8641414/HE_Test0506_1.zip)

Thanks, could you help verify attached test HE?

**Comment by a1ive** [comment]
> > 
> 
> [HE_Test0506_1.zip](https://github.com/Faintsnow/HE/files/8641414/HE_Test0506_1.zip)
> 
> Thanks, could you help verify attached test HE?

It works!
Thanks.

**Comment by Faintsnow** [comment]
> > > 
> > 
> > 
> > [HE_Test0506_1.zip](https://github.com/Faintsnow/HE/files/8641414/HE_Test0506_1.zip)
> > Thanks, could you help verify attached test HE?
> 
> It works! Thanks.
[HE_v1.22.5.6_Portable.zip](https://github.com/Faintsnow/HE/files/8641558/HE_v1.22.5.6_Portable.zip)

Thanks for your feedback.
Typo problem is already corrected in attached HE_v1.22.5.6_Portable.
BTW, Could you help provide CPU/SMBIOS/SPD log with this one?
Thanks.

**Comment by a1ive** [comment]
> > > > 
> > > 
> > > 
> > > [HE_Test0506_1.zip](https://github.com/Faintsnow/HE/files/8641414/HE_Test0506_1.zip)
> > > Thanks, could you help verify attached test HE?
> > 
> > 
> > It works! Thanks.
> > [HE_v1.22.5.6_Portable.zip](https://github.com/Faintsnow/HE/files/8641558/HE_v1.22.5.6_Portable.zip)
> 
> Thanks for your feedback. Typo problem is already corrected in attached HE_v1.22.5.6_Portable. BTW, Could you help provide CPU/SMBIOS/SPD log with this one? Thanks.

[report.txt](https://github.com/Faintsnow/HE/files/8641603/report.txt)
