### ISSUE TITLE
Access for Memory mapped registers 

### ISSUE THREAD

**Issue by DragonFrizzy** [Faintsnow/HE#3]
Could you please create option for memory mapped registers I tried to post message on your site but message board got deleted?

**Comment by Faintsnow** [comment]
Sorry, I don't known what's your meaning of "memory mapped registers".
You can access from Memory Space if it's Memory.
You can access from IO Space if it's Io Port.
If it's special registers and need special processing, it should be not common function for others, and you should write your own tool to meet your demand or access from CMD mode if it's possible.

**Comment by DragonFrizzy** [comment]
What I mean that I want to access to Fan Controller and PWM as you can see it says Internal memory maybe I'm wrong and it's not Mapped memory registers but I tried every single tab and wrote FE20 or FE20 and FE4F  I got what I want only FFFFF sometimes and 000 and sometimes just random numbers 
Pic is from datasheet Ene kb9012qf a3

![Screenshot_2022-06-25-14-49-29-48_a27b88515698e5a58d06d430da63049d.jpg](https://user-images.githubusercontent.com/75139483/175774270-2f57b253-106a-4d44-9931-b10c90aee0a6.jpg)

**Comment by Faintsnow** [comment]
Seems it's ECRAM, there's no common interface to access it.
Every ODM(or EC Vendor) has their special cmd to access it(Such as 2E/2F,4E/4F,6E/6F or 66/62)
If you know the access cmd, you should write your own tool to do such function.

PS: 
Actually, HE has such special function to RW internal ECRAM for company I worked(with our own cmd to access), but it's not common function, just for ourselves. So you can study the "Internal Memory Map" access method and write your own tool for it.

![20220625211841](https://user-images.githubusercontent.com/29788303/175775370-e049f070-6b0e-445c-93d4-1c5ea5e04a0a.jpg)

**Comment by DragonFrizzy** [comment]
Okay thanks sadly Im not a developer and have no idea how it works I mean how to create own tool. One question is it possible to add support for my chip of course if you want only many thanks for helping ❤️

**Comment by Faintsnow** [comment]
Sorry,I don't know the method to access the internal EC memory for your PC(may be you can ask your PC manufacturer for help).
And I can't do anything about it.

**Comment by DragonFrizzy** [comment]
Today I tried to send message to ene technology company maybe maybe they will explain to me how to access to Internal memory map asking Lenovo will make no sense because my laptop is locked yes I can try but only if ene wont explain to me or reply and could you please take a look on my chip maybe you can find a way to access to internal Memory map  
datasheet:https://drive.google.com/file/d/1FGc0qn5GGiFp37EKpOG3ocnW2LMmB_5s/view?usp=drivesdk
Of course only if you have time or want many thanks for helping replying to me I really appreciate that ♥️
