### ISSUE TITLE
Super I/O Chip support 

### ISSUE THREAD

**Issue by DragonFrizzy** [Faintsnow/HE#4]
Hi yes it's me again I found interested pages on my ene KB9012qf A4 EC IO chip datasheet 
![Screenshot_2022-06-28-11-47-56-11_a27b88515698e5a58d06d430da63049d.jpg](https://user-images.githubusercontent.com/75139483/176150010-0b8ec611-8fcf-4eeb-baae-b9c70d881b32.jpg)![Screenshot_2022-06-28-11-47-41-21_a27b88515698e5a58d06d430da63049d.jpg](https://user-images.githubusercontent.com/75139483/176150040-fd6baa9d-54c7-41ce-bec4-341604508837.jpg)![Screenshot_2022-06-28-11-46-56-74_a27b88515698e5a58d06d430da63049d.jpg](https://user-images.githubusercontent.com/75139483/176150066-8fed5e03-97fa-45d8-98a5-b58f1da303b5.jpg
And I remember on RWEverything I could change port for access 2E/2F if I'm sure there was 2E/2F and there is special Function registers page I would really appreciate that if you could add support for my chip maybe it's possible to add support on Super I/O tab because it's a Super I/O 
For more information here is datasheet of my chip:https://drive.google.com/file/d/1FGc0qn5GGiFp37EKpOG3ocnW2LMmB_5s/view?usp=drivesdk

How I said it would be really nice if you could just try to add support for my chip  many thanks in advance for helping ❤️
If you don't want okay I will try to ask fan control Softwares maybe they can help me

**Comment by Faintsnow** [comment]
You can try to access SIO with RW.
HE should works if RW can access such SIO, as HE supports all SIOs that RW supported and even more.
HE auto detect SIO via 2E/2F,4E/4F and 6E/6F and show SIO registers if find any supported or unknown SIO.

BTW,
I haven't used ENE EC before and no PC with ENE EC to test. 
I can't add a function that even I myselft  don't know or test.

**Comment by DragonFrizzy** [comment]
Oh maybe I can help you somehow because I use ene chip
