### ISSUE TITLE
AMD SMU access 

### ISSUE THREAD

**Issue by DragonFrizzy** [Faintsnow/HE#6]
Hi I wanted to ask again about smu access ![Screenshot_2022-07-12-06-59-41-43_a27b88515698e5a58d06d430da63049d.jpg](https://user-images.githubusercontent.com/75139483/178412384-4ee39e46-ad84-416c-af5a-7b108e7abd83.jpg)
Where should I put this values and I heard many times about pm table is there any way to access it for my CPU E1-1500 Apu because I found software pm table monitoring but only for Ryzen many thanks in advance for helping ❤️

**Comment by Faintsnow** [comment]
SMN Index/Data is not all the same, D00F0x060/D00F0x064 or D00F0x0A0/D00F0x0A4 or others.
And there is no common rule for SMN data on different platform event different PI.
You may try to access SMU via special Index/Data in PCI 0/0/0 if you know the Index No.

HE doesn't implement SMU accessing function.
And maybe you can refer to https://github.com/FlyGoat/ryzen_nb_smu

**Comment by Faintsnow** [comment]
Need manual operation in PCI configuration, doesn't plan to implement SMU related feature currently.

**Comment by DragonFrizzy** [comment]
Okay many thanks for helping ❤️
