### ISSUE TITLE
Question about DSDT cTDP, editing DSDT

### ISSUE THREAD

**Issue by DragonFrizzy** [Faintsnow/HE#7]
Dear HE I have one question 
In DSDT-AML decode I found cTDP and In some forums I saw that you can increase TDP with clover ... DSDT Editor in Mac So I have one question is it possible to somehow change TDP using HE I went to ACPI tables found memory adress wrote it on memory space worked then I went to AML decode and saw that cTDP was on offset 0x8A7 and there was FAN1 FAN2..
I wrote it on memory space:DFBEA800
and then 8A7 I didn't understand what bit should I change and one more problem I have no idea what tdp I have right now 
Upper offsets there was
OperationRegion (ECMM, system memory, 0xFF000000, 0x1000),
Field (ECMM, AnyAcc, Lock, Preserve)
Maybe I did something wrong I tried all Softwares still I can't monitor my CPU tdp so it would be nice if you could explain to me how to increase tdp if it's possible of course if TDP won't work how I said there was other interesting names GPUF,FAN1...
I have AMD 14h family CPU in datasheet I didn't found something useful for TDP value  increase 
Edit:Again many thanks for replying helping to me ❤️ I really appreciate that

**Comment by Faintsnow** [comment]
HE can't spontaneously do things that you slef don't know.
HE as a debug tool just provides interface for you to do something you known and want.
Every ODM has it own method for power control. 
Accoding to your description, the settings should controlled by EC and BIOS works with EC via H2RAM interface.
Maybe it worked via PECI,SWSMI,APML,ALIB or QEvent... You should understand the full power control flow chart first if you want to change settings by HE(if it can). But I can't help you to study that.

**Comment by Faintsnow** [comment]
Close as It has nothing to do with HE.
